#!/bin/sh
echo "Automated SFML Installer from source..."
platform='unknown' ;
unamestr=`uname` ;
if [ "$unamestr" = 'Linux' ] ; then
   platform='linux' ;
elif [ "$unamestr" = 'FreeBSD' ]; then
   platform='freebsd' ;
elif [ "$unamestr" = 'Darwin' ]; then
   platform='darwin' ;
fi
echo "OS: $platform"
#not used for now
processor='unknown' ;
unamestr=`uname -m`
if [ "$unamestr" = 'i686' ] ; then
   processor='x86' ;
elif [ "$unamestr" = 'x86_64' ] ; then
   processor='x86_64' ;
fi
echo "PROCESSOR: $processor"

if [ ! -e "./deps" ] ; then
   echo "Making deps directory..."
   mkdir "deps"
fi
cd deps
if [ "$platform" != 'darwin' ] ; then
   #openal
   if [ ! -e "./openalsoft" ] ; then
      echo "Downloading OpenALSoft source"
      `/usr/bin/curl -o "./openalsoft.tar.bz2" "http://kcat.strangesoft.net/openal-releases/openal-soft-1.12.854.tar.bz2"`
      `tar -xvf "openalsoft.tar.bz2"`
      rm ./*.tar.bz2
      mv openal-soft*/ openalsoft
   
      cd openalsoft/build
      echo "Making OpenALSoft"
      `cmake ..`
      `make`
      echo "Installing OpenALSoft"
      `sudo make install`
      cd ../..
   else
      echo "OpenALSoft already exists, remove directory for a fresh compile"
   fi
   #libsndfile
   if [ ! -e "./libsndfile" ] ; then
      echo "Downloading libsndfile source"
      `/usr/bin/curl -o "libsndfile.tar.gz" "http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.21.tar.gz"`
      `tar -xvf "libsndfile.tar.gz"`
      rm ./*.tar.gz
      mv libsndfile*/ libsndfile
   
      cd libsndfile
      echo "Making libsndfile"
      `./configure`
      `make`
      echo "Installing libsndfile"
      `sudo make install`
      cd ..
   else
      echo "libsndfile already exists, remove directory for a fresh compile"
   fi
fi
#SFML
if [ ! -e "./sfml" ] ; then
   echo "Downloading SFML source"
   `/usr/bin/svn checkout "http://sfml.svn.sourceforge.net/svnroot/sfml/tags/1.6" "sfml"`
   cd sfml
   
   echo "Making SFML"
   `make`
   cd ..
else
   echo "sfml already exists, remove directory for a fresh compile"
   cd sfml
fi

if [ "$platform" = 'darwin' ] ; then
   echo "Installing External Frameworks"
   echo "OpenAL"
   sudo cp -r extlibs/bin/OpenAL.framework /Library/Frameworks
   
   echo "sndfile"
   if [ "$processor" = 'x86_64' ] ; then
      sudo cp -r extlibs/bin/x86_64/sndfile.framework /Library/Frameworks
   else
      sudo cp -r extlibs/bin/sndfile.framework /Library/Frameworks
   fi
fi

cd ../..
echo "Building node-sfml"
if [ -e "./build" ] ; then
   node-waf distclean
fi
node-waf configure build
if [ ! -e "./lib" ] ; then
   mkdir lib
fi
cp ./build/default/nodesfml.node ./lib/
